services:
  sshbridge:
    image: ghcr.io/nghoang1288/sshbridge:latest
    container_name: sshbridge
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - sshbridge-data:/app/data
    environment:
      PORT: "8080"
    depends_on:
      - guacd
    networks:
      - sshbridge-net

  guacd:
    image: guacamole/guacd:1.6.0
    container_name: guacd
    restart: unless-stopped
    ports:
      - "4822:4822"
    networks:
      - sshbridge-net

volumes:
  sshbridge-data:
    driver: local

networks:
  sshbridge-net:
    driver: bridge
